### PR TITLE
Add TypeScript definitions.

### PR DESCRIPTION
**Pull request by slig**
Following on #33, here's the PR.

There're a couple of things I'm not 100% sure, though. 

I don't think that the types `Square`, `Piece`, `Position` and `CustomPieces` have to be exported, so I didn't export them. Also the `roughSquare` receives a `squareElement` which I believe the appropriate type is `SVGElement`.

Thank you for your time on this!

### CODE REVIEW

**Comment by willb335** [comment]
> I don't think that the types Square, Piece, Position and CustomPieces have to be exported, so I didn't export them.

That sounds fine if somebody needs them exported I can look into it.

Could you make a new pull request running ```npm run commit``` and then just follow the prompts and add it as a 'doc' change?  This helps to integrate the new commits into versioning. 

I'm afraid if I amend the commit myself then it won't recognize you as a contributor.

**Comment by willb335** [comment]
on second thought, this won't affect versioning since it is not a feature change, I'll merge this in.  Thanks!

**Comment by slig** [comment]
Thank you very much!

**Pull request merged**
