### PR TITLE
feat(pieces): customize pieces via render prop

### PR DESCRIPTION
**Pull request by willb335**
#20 

@csharptest mind taking a look at this pull request? Specifically the ```renderChessPiece``` function in Piece.js?

The render prop offers one argument, the squareWidth.

This is a far superior way to handle custom pieces.  Thanks!

### CODE REVIEW

**Comment by csharptest** [comment]
Well, first I'll say that code looks a lot cleaner than before, great work.

It appears you are changing the method signature from `function( {width, height, piece} )` to simply be `function( size )`?

If I understand this pull request correctly, I have some feedback:

1. This does not match the behavior of the `<svg>` render as it provides a width/height that are calculated from different variables. While I understand that today these are derived from `Chessboard.width`, this may not always be the case. Regardless what the answer is here, it should match the built-in rendering.

2. Providing a structure as opposed to ordinal parameters is preferable to me for javascript/typeless APIs. This allows me to simply interrogate the RTTI via the debugger or `console.log([...arguments])` and discover the arguments and also meaning from the structure's member names (I guess I'm not big on documents). The use of a structure argument is also more extensible, see the next bullet.

3. As I've continued working I realized I also need the current square of the piece being rendered so that I can display threats and other related styles. This has me thinking that the argument should be derived from the calling parameters, more like the following:
```javscript
// src/Chessboard/Piece.js (line: 43)
  const args = {
    piece,
    size: width, // or width & height
    currentSquare,
    isDragging,
    sourceSquare,
    targetSquare,
  },

{typeof pieces[piece] === 'function' ? (
        pieces[piece](args)
      ) : (
        <svg viewBox={`1 1 43 43`} width={width / 8} height={width / 8}>
          <g>{pieces[piece]}</g>
        </svg>
      )}
```
Note: Is there some duplication between currentSquare and either sourceSquare/targetSquare? It seems like current + target would make the most sense to external consumers.

**Comment by willb335** [comment]
Thanks for the feedback.

> 2. Providing a structure as opposed to ordinal parameters is preferable...

Makes sense to me, I will keep this in mind as I maintain the project.  

>3. As I've continued working I realized I also need the current square of the piece being rendered so that I can display threats and other related styles...

This is great.  I want to make the library easily customizable and this is a big step in that direction.

> seems like current + target would make the most sense to external consumers

I like source + target, mainly because it's consistent with ReactDnD's api.  If you think that's confusing in anyway, please let me know

> 1. This does not match the behavior of the <svg> render...

I can't quite follow.  Can you please explain this a little more?  

Thanks again for the help

**Comment by willb335** [comment]
@csharptest
Please take a look at the renderChessPiece function in Piece.js starting at line 9.

Feel free to play with Demo.js to see the changes in action.  Any feedback is appreciated

**Comment by willb335** [comment]
The ```//undefined when dragging comment``` is getting ahead of myself, the more common use case will just to use ```isDragging``` to change the piece image on drag.  

```targetSquare``` and ```currentSquare``` are redundant in this case.  I need to refactor the code at some point to make the difference between ```currentSquare``` and ```targetSquare``` more clear.  

```targetSquare``` and ```sourceSquare``` come from the diff of positions being passed through the ```position``` prop.  when the position is set via a manual drop, then there is no source and target squares, there is a drop target and a  source piece and source square  that are set when dragging begins.  

This is confusing even for me, I need to do a better job naming.  Perhaps, ```sourcePiece : { e5: 'wK' }``` and ```dropTarget: 'e6'```

**Comment by csharptest** [comment]
I think going with structures more will help in the long run and create fewer breaking changes for consumers.  I'm all for sourcePiece being a structure; however, I would use something like:
```
{
  sourcePiece: {
    piece: 'wK',
    square: 'e5'
  }
}
```
This would alleviate the need for using Object.keys(...) etc to determine the square.

**Comment by willb335** [comment]
Thanks!

I'm going to take sometime to think about these new features.  This is the first real deviation from chessboard.js, so the first time I have to think about the direction of the project :)

I want to make sure that the props are flexibile, I want to minimize niche props

**Comment by csharptest** [comment]
Ack, I can certainly understand. I have not used chessboard.js before, so you are more aware of it's abilities in that regard.

**Comment by willb335** [comment]
chessboardjsx 2.0 released here :
https://github.com/willb335/chessboardjsx/commit/38ce5ebe0121537b17cf3b0575fd490c961ca628

**Pull request closed without merging**
